# Generated by Django 4.2.7 on 2023-12-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('posicion', models.CharField(max_length=3)),
            ],
        ),
    ]
