# Generated by Django 4.2.7 on 2023-12-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_equipo', '0003_alter_jugador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores_perfiles/'),
        ),
    ]
