# Generated by Django 4.2.7 on 2023-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0002_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
